=== shoopi/get-controller/WebContent/WEB-INF/eventType/predefinedEventTypes/FlightDiversion.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="FlightDiversion.xsd"
	targetNamespace="FlightDiversion.xsd" elementFormDefault="qualified">
	<xs:element name="flightTrace">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="flightId" type="xs:integer" minOccurs="1"
					maxOccurs="1" />
				<xs:element name="departure">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="origin" type="xs:string" />
							<xs:element name="departurelatitude" type="xs:double"
								minOccurs="1" maxOccurs="1" />
							<xs:element name="departurelongitude" type="xs:double"
								minOccurs="1" maxOccurs="1" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="arrival">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="destination" type="xs:string" />
							<xs:element name="arrivallatitude" type="xs:double"
								minOccurs="1" maxOccurs="1" />
							<xs:element name="arrivallongitude" type="xs:double"
								minOccurs="1" maxOccurs="1" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="timestamp" type="xs:dateTime"
					minOccurs="1" maxOccurs="1" />
				<xs:element name="certainty" type="xs:string" />
				<xs:element name="aircraftId" type="xs:integer" />
				<xs:element name="flightNumber" type="xs:string" />
				<xs:element name="latitude" type="xs:double" minOccurs="1"
					maxOccurs="1" />
				<xs:element name="longitude" type="xs:double" minOccurs="1"
					maxOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== shoopi/get-controller/FlightDiversionEvent.xml
<?xml version="1.0" encoding="UTF-8"?>
<flightTrace xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="FlightDiversion.xsd">
  <flightId>1234</flightId>
  <departure>
    <origin>str1234</origin>
    <departurelatitude>3.1415926535</departurelatitude>
    <departurelongitude>3.1415926535</departurelongitude>
  </departure>
  <arrival>
    <destination>Frankfurt</destination>
    <arrivallatitude>50.03333</arrivallatitude>
    <arrivallongitude>8.57056</arrivallongitude>
  </arrival>
  <timestamp>2012-12-13T12:12:12</timestamp>
  <aircraftId>1234</aircraftId>
  <certainty>0.89</certainty>
  <flightNumber>str1234</flightNumber>
  <latitude>50.1415926535</latitude>
  <longitude>8.1415926535</longitude>
</flightTrace>
