=== shoopi/get-controller/WebContent/WEB-INF/eventType/unexpectedtrafficGETService.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="unexpectedTrafficGETService.xsd" targetNamespace="unexpectedTrafficGETService.xsd" elementFormDefault="qualified">
<!--  
   <annotation>
        <appinfo>Important Note</appinfo>
        <documentation xml:lang="en">
            The delay is given in minutes as integer.
        </documentation>
    </annotation>
    -->
    <xs:element name="unexpectedTraffic">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="title" type="xs:string"/>
                <xs:element name="source" type="xs:integer"/>
                <xs:element name="delay" type="xs:integer"/>
                <xs:element name="timestamp" type="xs:date"/>
                <xs:element name="coordinate">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="latitude" type="xs:string"/>
                            <xs:element name="longitude" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== shoopi/get-controller/unexpectedTraffic.xml
<?xml version="1.0" encoding="UTF-8"?>
<unexpectedTraffic xmlns="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="unexpectedtrafficGETService.xsd">
	<title>On the way from Roosendaal to Rotterdam roads are blocked because of a truck accident. The estimated 
		time of clearing is currently unpredictable.
	</title>
	<source>1849</source>
    <delay>30</delay>
	<timestamp>2012-02-01T15:52:44.694</timestamp>
		<coordinate>
			<latitude>51.94683</latitude>
			<longitude>4.03339</longitude>
		</coordinate>
</unexpectedTraffic>
